### ISSUE TITLE
make_dataset.py giving  an issue in build_embeddings

### ISSUE THREAD

**Issue by VinACE** [GauthierDmn/question_answering#1]
File downloaded successfully!
File downloaded successfully!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 442/442 [01:06<00:00,  7.00it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:06<00:00,  4.08it/s]

Vocabulary created successfully.
Traceback (most recent call last):
  File "make_dataset.py", line 228, in <module>
    max_len_word=config.max_len_word, is_train=True)
  File "make_dataset.py", line 150, in extract_features
    vec_size=config.word_embedding_size)
  File "/home/ofsdms/question_answering/utils.py", line 96, in build_embeddings
    vector = np.asarray(values[1:], dtype="float32")
  File "/home/ofsdms/qanet/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)

**Comment by VinACE** [comment]
I added a try catch to skip the  error will that hurt
                try:
                    vector = np.asarray(values[1:], dtype="float32")
                except ValueError:
                    print("Oops!  That was no valid number.  Try again...")

**Comment by GauthierDmn** [comment]
Thanks for reporting the issue, I'll fix it most likely tomorrow! ;)

**Comment by GauthierDmn** [comment]
Hi VinAce,

-Did you download GloVe word embedding at this address: http://nlp.stanford.edu/data/glove.6B.zip
-Could you print the variable "values" to see what you are getting?

G.
