### ISSUE TITLE
torch.from_numpy  loading error of word_embedding_matrix

### ISSUE THREAD

**Issue by VinACE** [GauthierDmn/question_answering#2]
$ python train.py

> /demo-mount/question_answering/train.py(75)<module>()
-> with open(os.path.join(config.train_dir, "word_embeddings.pkl"), "rb") as e:
(Pdb)
(Pdb) n
> /demo-mount/question_answering/train.py(76)<module>()
-> word_embedding_matrix = pickle.load(e)
(Pdb) n
> /demo-mount/question_answering/train.py(77)<module>()
-> with open(os.path.join(config.train_dir, "char_embeddings.pkl"), "rb") as e:
(Pdb) n
> /demo-mount/question_answering/train.py(78)<module>()
-> char_embedding_matrix = pickle.load(e)
(Pdb) n
> /demo-mount/question_answering/train.py(81)<module>()
-> with open(os.path.join(config.train_dir, "word2idx.pkl"), "rb") as f:
(Pdb) n
> /demo-mount/question_answering/train.py(82)<module>()
-> word2idx = pickle.load(f)
(Pdb) n
> /demo-mount/question_answering/train.py(84)<module>()
-> idx2word = dict([(y, x) for x, y in word2idx.items()])
(Pdb) n
> /demo-mount/question_answering/train.py(87)<module>()
-**> word_embedding_matrix = torch.from_numpy(np.array(word_embedding_matrix)).type(torch.float) # changed float32 to float**
(Pdb) n
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.
> /demo-mount/question_answering/train.py(87)<module>()
-> word_embedding_matrix = torch.from_numpy(np.array(word_embedding_matrix)).type(torch.float) # changed float32 to float

kindly have look at , I am getting word_embedding_matrix load error in train.py

**Comment by GauthierDmn** [comment]
Hi VinAce,

What is the type of your word_embedding_matrix object? If you created your embedding matrix successfully, you normally have it as a list.
 
G.

**Comment by VinACE** [comment]
$ python train.py --epochs 2
word_embedding_matrix type is
<class 'list'>
